Controllers/InformController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Scheduler_Project.Models;
using Scheduler_Project.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace Scheduler_Project.Controllers
{
    public class InformController : Controller
    {
        //Http Client is the proper way to connect to a webapi
        //https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;


        static InformController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);
            client.BaseAddress = new Uri("https://localhost:44356/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: Inform/List
        public ActionResult List()
        {
            string url = "InformData/GetInforms";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<InformDto> SelectedInforms = response.Content.ReadAsAsync<IEnumerable<InformDto>>().Result;
                return View(SelectedInforms);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Inform/Details/1
        public ActionResult Details(int id)
        {
            ShowInform ViewModel = new ShowInform();
            string url = "InformData/FindInform/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into Inform Data Transfer Object
                InformDto SelectedInform = response.Content.ReadAsAsync<InformDto>().Result;
                ViewModel.Inform = SelectedInform;

                //Find the Project for Inform by Id
                url = "ProjectData/FindProjectForInform/" + id;
                response = client.GetAsync(url).Result;
                Debug.WriteLine(response.StatusCode);
                ProjectDto SelectedProject = response.Content.ReadAsAsync<ProjectDto>().Result;
                ViewModel.Project = SelectedProject;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: Project/Create
        [HttpGet]
        public ActionResult Create()
        {
            UpdateInform ViewModel = new UpdateInform();
            //get information about Projects this Inform is in.
            string url = "ProjectData/GetProjects";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<ProjectDto> PotetnialProjects = response.Content.ReadAsAsync<IEnumerable<ProjectDto>>().Result;
            ViewModel.Allprojects = PotetnialProjects;
            return View(ViewModel);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="InformInfo"></param>
        /// <returns></returns>
        // POST: Inform/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Inform InformInfo)
        {
            Debug.WriteLine(InformInfo.InfoData);
            string url = "InformData/AddInform";
            //Debug.WriteLine(jss.Serialize(InformInfo));
            HttpContent content = new StringContent(jss.Serialize(InformInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                int InformID = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("List", "Category");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Inform/Edit/2
        [HttpGet]
        public ActionResult Edit(int id)
        {
            UpdateInform ViewModel = new UpdateInform();

            string url = "InformData/FindInform/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                InformDto SelectedInform = response.Content.ReadAsAsync<InformDto>().Result;
                ViewModel.Inform = SelectedInform;

                url = "ProjectData/GetProjects";
                response = client.GetAsync(url).Result;
                IEnumerable<ProjectDto> InformsProject = response.Content.ReadAsAsync<IEnumerable<ProjectDto>>().Result;
                ViewModel.Allprojects = InformsProject;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Inform/Edit/2
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Inform InformInfo)
        {
            Debug.WriteLine(InformInfo.InfoData);
            string url = "InformData/UpdateInform/" + id;
            Debug.WriteLine(jss.Serialize(InformInfo));
            HttpContent content = new StringContent(jss.Serialize(InformInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List", "Category");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Inform/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "InformData/FindInform/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                InformDto SelectedInform = response.Content.ReadAsAsync<InformDto>().Result;
                return View(SelectedInform);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Inform/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "InformData/DeleteInform/" + id;
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List", "Category");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public ActionResult Error()
        {
            return View();
        }
    }
}

Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Scheduler_Project.Models;
using Scheduler_Project.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace Scheduler_Project.Controllers
{
    public class ProjectController : Controller
    {
        //Http Client is the proper way to connect to a webapi
        //https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;
        public object CategoryID { get; private set; }

        static ProjectController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);
            client.BaseAddress = new Uri("https://localhost:44356/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: Project/List
        public ActionResult List()
        {
            string url = "ProjectData/GetProjects";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<ProjectDto> SelectedProjects = response.Content.ReadAsAsync<IEnumerable<ProjectDto>>().Result;
                return View(SelectedProjects);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Project/Details/1
        [HttpGet]
        public ActionResult Details(int id)
        {
            ShowProject ViewModel = new ShowProject();
            string url = "ProjectData/FindProject/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into Project Data Transfer Object
                ProjectDto SelcetedProject = response.Content.ReadAsAsync<ProjectDto>().Result;
                ViewModel.Project = SelcetedProject;

                //Find the Category for Project by Id
                url = "CategoryData/FindCategoryForProject/" + id;
                response = client.GetAsync(url).Result;
                Debug.WriteLine(response.StatusCode);
                CategoryDto SelectedCategory = response.Content.ReadAsAsync<CategoryDto>().Result;
                ViewModel.Category = SelectedCategory;

                //Get the Inform for Project by Id
                url = "ProjectData/GetInformForProject/" + id;
                response = client.GetAsync(url).Result;
                Debug.WriteLine(response.StatusCode);
                IEnumerable<InformDto> SelectedInforms = response.Content.ReadAsAsync<IEnumerable<InformDto>>().Result;
                ViewModel.ProjectInforms = SelectedInforms;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: Category/Create
        [HttpGet]
        public ActionResult Create()
        {
            UpdateProject ViewModel = new UpdateProject();
            //get information about Categories this Project is in.
            string url = "CategoryData/GetCategories";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<CategoryDto> PotetnialCategories = response.Content.ReadAsAsync<IEnumerable<CategoryDto>>().Result;
            ViewModel.Allcategories = PotetnialCategories;
            return View(ViewModel);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="ProjectInfo"></param>
        /// <returns></returns>
        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Project ProjectInfo)
        {
            Debug.WriteLine(ProjectInfo.ProjectName);
            string url = "ProjectData/AddProject";
            //Debug.WriteLine(jss.Serialize(ProjectInfo));
            HttpContent content = new StringContent(jss.Serialize(ProjectInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                //int ProjectID = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", "Category", new { id = CategoryID });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Project/Edit/2
        [HttpGet]
        public ActionResult Edit(int id)
        {
            UpdateProject ViewModel = new UpdateProject();

            string url = "ProjectData/FindProject/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                ProjectDto SelectedProject = response.Content.ReadAsAsync<ProjectDto>().Result;
                ViewModel.Project = SelectedProject;

                url = "CategoryData/GetCategories";
                response = client.GetAsync(url).Result;
                IEnumerable<CategoryDto> ProjectsCategory = response.Content.ReadAsAsync<IEnumerable<CategoryDto>>().Result;
                ViewModel.Allcategories = ProjectsCategory;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="ProjectInfo"></param>
        /// <returns></returns>
        // POST: Project/Edit/2
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Project ProjectInfo)
        {
            Debug.WriteLine(ProjectInfo.ProjectName);
            string url = "ProjectData/UpdateProject/" + id;
            Debug.WriteLine(jss.Serialize(ProjectInfo));
            HttpContent content = new StringContent(jss.Serialize(ProjectInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Project/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "ProjectData/FindProject/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                ProjectDto SelectedProject = response.Content.ReadAsAsync<ProjectDto>().Result;
                return View(SelectedProject);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Project/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "ProjectData/DeleteProject/" + id;
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List", "Category");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public ActionResult Error()
        {
            return View();
        }
    }
}

Views/Inform/Create.cshtml
@model Scheduler_Project.Models.ViewModels.UpdateInform

@{
    ViewBag.Title = "Create";
}

<h2>Create A New Inform</h2>

@using (Html.BeginForm())
{
    //This will set a hidden input field with value "_RequestVerificationToken"
    //The PlayerController Create Method will look for this token
    //This helps secure the Create() method from being called from other pages.
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Make Sure to fill all the fields</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">

            <div class="form-group">
                @Html.LabelFor(model => model.Inform.InfoData, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Inform.InfoData, new { htmlAttributes = new { @class = "form-space", Name = "InfoData" } })
                    @Html.ValidationMessageFor(model => model.Inform.InfoData, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Inform.InfoPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Inform.InfoPhoneNumber, new { htmlAttributes = new { @class = "form-space", Name = "InfoPhoneNumber", type = "phonenumber"} })
                    @Html.ValidationMessageFor(model => model.Inform.InfoPhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Inform.InfoEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Inform.InfoEmail, new { htmlAttributes = new { @class = "form-space", Name = "InfoEmail", type = "email" } })
                    @Html.ValidationMessageFor(model => model.Inform.InfoEmail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Inform.InfoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Inform.InfoUrl, new { htmlAttributes = new { @class = "form-space", Name = "InfoUrl", type = "url" } })
                    @Html.ValidationMessageFor(model => model.Inform.InfoUrl, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Inform.ProjectID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="ProjectID">
                        @foreach (var Project in Model.Allprojects)
                        {
                            <option value="@Project.ProjectID">@Project.ProjectName</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="button btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    <a href="javascript:void(0);" onclick="history.go(-1);">Back to Details</a>
    <!--Html.ActionLink("Back to Details", "Details", new { id = Model.Inform.ProjectID })-->
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Inform/DeleteConfirm.cshtml
@model Scheduler_Project.Models.InformDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>DeleteConfirm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Once it is deleted it can't be undone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InformID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InformID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InfoData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InfoData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InfoPhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InfoPhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InfoEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InfoEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InfoUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InfoUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectID)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Inform", new { id = Model.InformID }))
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Back to Details", "Details", new { id = Model.InformID })
    </div>
    }
</div>

Views/Inform/Details.cshtml
@model Scheduler_Project.Models.ViewModels.ShowInform
<link rel="stylesheet" href="~/Content/Inform/inform.css" type="text/css" />
@{
    ViewBag.Title = "Details";
}

<h2><span class="convert__white">Inform Reminder : </span>@Html.DisplayFor(model => model.Inform.InfoData)</h2>
<hr />

<div style="display:inline-block;" class="portion__all">
    <div class="portion__row">
        @if (Model.Inform.InfoPhoneNumber != null)
        {
            <div class="project__item">
                <h4 style="color:#4f6b43;">
                    @Html.DisplayNameFor(model => model.Inform.InfoPhoneNumber):
                </h4>
                <p>
                    <i class="fa fa-phone-square"></i> <a href="tel:@Html.DisplayFor(model => model.Inform.InfoPhoneNumber)" target="_blank">
                        @Html.DisplayFor(model => model.Inform.InfoPhoneNumber)
                    </a>
                </p>
            </div>
        }
        @if (Model.Inform.InfoEmail != null)
        {
            <div class="project__item">
                <h4 style="color:#4f6b43;">
                    @Html.DisplayNameFor(model => model.Inform.InfoEmail):
                </h4>
                <p>
                    <i class="fa fa-envelope"></i> <a href="mailto:@Html.DisplayFor(model => model.Inform.InfoEmail)" target="_blank">
                        @Html.DisplayFor(model => model.Inform.InfoEmail)
                    </a>
                </p>
            </div>
        }
        @if (Model.Inform.InfoUrl != null)
        {
            <div class="project__item">
                <h4 style="color:#4f6b43;">
                    @Html.DisplayNameFor(model => model.Inform.InfoUrl):
                </h4>
                <p>
                    <i class="fa fa-link"></i> <a href="@Html.DisplayFor(model => model.Inform.InfoUrl)" target="_blank">
                        @Html.DisplayFor(model => model.Inform.InfoUrl)
                    </a>
                </p>
            </div>
        }
       </div>
</div>

<div>
    @Html.ActionLink("Delete Information", "DeleteConfirm", new { id = Model.Inform.InformID }, new { @class = "delete__button" })
    @Html.ActionLink("Edit Information", "Edit", new { id = Model.Inform.InformID }, new { @class = "edit__button" })
    @Html.ActionLink("Go Back To Project", "Details", "Project", new { id = Model.Inform.ProjectID }, new { @class = "back__button" })
</div>

Views/Inform/Edit.cshtml
@model Scheduler_Project.Models.ViewModels.UpdateInform

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Inform", new { id = Model.Inform.InformID }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Update Inform</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Inform.InformID, new { Name = "InformID" })
        <div class="row">
            <div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Inform.InfoData, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Inform.InfoData, new { htmlAttributes = new { @class = "form-space", Name = "InfoData" } })
                        @Html.ValidationMessageFor(model => model.Inform.InfoData, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Inform.InfoPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Inform.InfoPhoneNumber, new { htmlAttributes = new { @class = "form-space", Name = "InfoPhoneNumber", type = "phonenumber" } })
                        @Html.ValidationMessageFor(model => model.Inform.InfoPhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Inform.InfoEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Inform.InfoEmail, new { htmlAttributes = new { @class = "form-space", Name = "InfoEmail", type = "email" } })
                        @Html.ValidationMessageFor(model => model.Inform.InfoEmail, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Inform.InfoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Inform.InfoUrl, new { htmlAttributes = new { @class = "form-space", Name = "InfoUrl", type = "url" } })
                        @Html.ValidationMessageFor(model => model.Inform.InfoUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Inform.ProjectID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select name="ProjectID">
                            @foreach (var Project in Model.Allprojects)
                            {
                                //Auto-selects the Project the Inform is currently assigned to
                                string selected = "";
                                if (Model.Inform.ProjectID == Project.ProjectID)
                                {
                                    selected = "";
                                }
                                <option value="@Project.ProjectID" @selected>@Project.ProjectName</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="button btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Details", "Details", new { id = Model.Inform.InformID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Inform/List.cshtml
@model IEnumerable<Scheduler_Project.Models.InformDto>

@{
    ViewBag.Title = "List";
}

<h2>Inform List</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Inform", new { @class = "button btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.InfoData)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InfoPhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InfoEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InfoUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectID)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InfoData)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InfoPhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InfoEmail)
            </td>
            <td class="col-sm-1">
                @Html.DisplayFor(modelItem => item.InfoUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectID)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.InformID }) |
                @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.InformID }, new { @class = "text-danger" })
            </td>
        </tr>
    }

</table>